name: "Testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: .*testdata/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          DEFAULT_BRANCH: master

  test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: hellofresh/kangal-ghz:local
          push: false

      - name: Build dummy gRPC server Docker image
        uses: docker/build-push-action@v2
        with:
          tags: greeter_server:local
          file: ./testdata/Dockerfile
          context: ./testdata
          push: false

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Load docker images into kind cluster
        run: |
          kind load docker-image greeter_server:local
          kind load docker-image hellofresh/kangal-ghz:local
      
      - name: Kangal Integration Tests
        run: |
          ./ci/integration-tests.sh
